name: Deploy to server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: matheusvanzan/sshpass-action@v2
        with: 
          host: ${{ secrets.SERVER_IP }}
          port: 22
          user: ${{ secrets.SERVER_USERNAME }}
          pass: ${{ secrets.SERVER_SSH_PASSWORD }}
          run: |
            cd ~/Desktop/ics3u-project
            git pull origin main
            npm install
            pm2 restart index